<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>WebCon.Plugins.Signing.Autenti</RootNamespace>
    <AssemblyName>WebCon.Plugins.Signing.Autenti</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>temporary_key.snk</AssemblyOriginatorKeyFile>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Api\DocumentLockException.cs" />
    <Compile Include="Api\AutentiApiException.cs" />
    <Compile Include="Api\HttpResponseMessageExtensions.cs" />
    <Compile Include="Api\Models\AssertionPayload.cs" />
    <Compile Include="Api\Models\AutentiConsts.cs" />
    <Compile Include="Api\Models\ApiLinkResponse.cs" />
    <Compile Include="Api\Models\ReminderChallengeRequest.cs" />
    <Compile Include="Api\Models\ReminderChallengeResponse.cs" />
    <Compile Include="Api\Models\DocumentDetailsResponse.cs" />
    <Compile Include="Api\Models\DocumentFileInfo.cs" />
    <Compile Include="Api\Models\IdentificationProfile.cs" />
    <Compile Include="Common\AuthorizationConfig.cs" />
    <Compile Include="Common\DocumentStatusInput.cs" />
    <Compile Include="GetDocument\GetDocumentAction.cs" />
    <Compile Include="GetDocument\GetDocumentConfig.cs" />
    <Compile Include="GetStatuses\GetDocumentStatusAction.cs" />
    <Compile Include="GetStatuses\GetDocumentStatusConfig.cs" />
    <Compile Include="GetStatuses\GetRecipientsSignatureStatusAction.cs" />
    <Compile Include="GetStatuses\GetRecipientsSignatureStatusConfig.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Api\AutentiApiService.cs" />
    <Compile Include="Api\AutentiClientProvider.cs" />
    <Compile Include="Api\AutentiHttpClient.cs" />
    <Compile Include="Api\DocumentProcessRequestBuilder.cs" />
    <Compile Include="Api\IAutentiApiService.cs" />
    <Compile Include="Api\IAutentiHttpClient.cs" />
    <Compile Include="Api\IDocumentProcessRequestBuilder.cs" />
    <Compile Include="Api\Models\DocumentProcessRequest.cs" />
    <Compile Include="Api\Models\DocumentProcessResponse.cs" />
    <Compile Include="Api\Models\RequestDto.cs" />
    <Compile Include="SendForSignature\Providers\AttachmentsProvider.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\CoreDataEnricher.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\IItemListRowContext.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\IPartyEnricher.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\ItemListRowContext.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\OrganizationRepresentativeEnricher.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\SignatureEnricher.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\SigningOrderEnricher.cs" />
    <Compile Include="SendForSignature\Providers\Enrichers\SmsEnricher.cs" />
    <Compile Include="SendForSignature\Providers\IAttachmentsProvider.cs" />
    <Compile Include="SendForSignature\Providers\IPartiesProvider.cs" />
    <Compile Include="SendForSignature\Providers\OrganizationSenderProvider.cs" />
    <Compile Include="SendForSignature\Providers\PartiesProvider.cs" />
    <Compile Include="SendForSignature\Providers\PartiesValidator.cs" />
    <Compile Include="SendForSignature\SendForSignatureAction.cs" />
    <Compile Include="SendForSignature\SendForSignatureConfig.cs" />
    <Compile Include="SendReminder\SendReminderAction.cs" />
    <Compile Include="SendReminder\SendReminderConfig.cs" />
    <Compile Include="SignLink\GetSignLink.cs" />
    <Compile Include="SignLink\GetSignLinkConfig.cs" />
    <Compile Include="Sources\DocumentStatus.cs" />
    <Compile Include="Sources\RecipentRoles.cs" />
    <Compile Include="Sources\RecipentRolesConfig.cs" />
    <Compile Include="Sources\RecipientSignatureStatus.cs" />
    <Compile Include="Sources\SignatureTypes.cs" />
    <Compile Include="Sources\SignatureTypesConfig.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="SendForSignature\Diagram.md" />
    <None Include="WebCon.Plugins.Signing.Autenti.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="temporary_key.snk" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Publish\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WEBCON.BPS.2026.SDK.Libraries" Version="26.1.1.26">
		<ExcludeAssets>runtime</ExcludeAssets>
	</PackageReference>
  </ItemGroup>
</Project>